var misec=0,sec=0,min=0,hr=0;
        var x;
        function timer(){
            misec++;
        if(misec<9){
           document.getElementById("misec").innerHTML="0"+misec;
        }
        if(misec>9){
            document.getElementById("misec").innerHTML=misec;
        }
        if(misec>99){
            sec++;
            document.getElementById("sec").innerHTML="0"+sec;
            misec=0;
            document.getElementById("misec").innerHTML="0"+0;
        }
        if(sec<9){
           document.getElementById("sec").innerHTML="0"+sec;
        }
        if(sec>9){
            document.getElementById("sec").innerHTML=sec;
        }
        if(sec>59){
            min++;
            document.getElementById("min").innerHTML="0"+min;
            sec=0;
            document.getElementById("sec").innerHTML="0"+0;
        }
        if(min<9){
           document.getElementById("min").innerHTML="0"+min;
        }
        if(min>9){
            document.getElementById("min").innerHTML=min;
        }
        if(min>59){
            hr++;
            document.getElementById("hr").innerHTML="0"+hr;
            min=0;
            document.getElementById("min").innerHTML="0"+0;
        }
    }
   document.getElementById("one").addEventListener("click",function(e){
             x=setInterval(timer,10);
        })
        document.getElementById("two").addEventListener("click",function(e){
            clearInterval(x);
        })
        document.getElementById("three").addEventListener("click",function(e){
            clearInterval(x);
            hr=0;min=0;sec=0;misec=0;
            document.getElementById("misec").innerHTML="00";
            document.getElementById("sec").innerHTML="00";
            document.getElementById("min").innerHTML="00";
            document.getElementById("hr").innerHTML="00";
        })
